[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20
startup_mode = "Maximized"

decorations = "Buttonless"
#opacity = 0.92
#blur = true
[colors]
[colors.primary] 
background = '#222A2E'  # Здесь задайте нуллжный вам цвет в формате HEX

[font]
normal.family = "FiraCode Nerd Font"
size = 15.0

[terminal]
shell = "/opt/homebrew/bin/fish"
